version: "3.7"
services: 
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    volumes: 
      - ./backend/api:/code
    networks:
      - private-network
    ports: 
     - 9010:3000
    command: npx nodemon app.js
  db:
    image: mongo
    ports: 
     - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: mydb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes: 
      - db_data:/data/db
    networks:
      - private-network
volumes: 
  db_data:

networks:
  private-network: